# write a program time module
import time
second=time.time()
print("second since epoch:",second)
local_time=time.ctime(1730462779.285724)
print("local time:",local_time)
print("printed")
time.sleep(3)
print("hello")
current_time=time.localtime()
print("current time:",current_time)
result=time.gmtime(1730462799)
print("result:",result)
time_tuple = (2024, 11, 12, 6, 19, 4, 0, 0, -1)
second=time.mktime(time_tuple)
print(second)
name_tuple=time.localtime()
time_string = time.strftime("%m %d %y %H %M %S", name_tuple)
print(time_string)
time_string="24 oct 2024"
result = time.strptime(time_string,"%d %b %Y" )
print(result)
readable_time=time.asctime(time.localtime())
print(f"readable local time,{readable_time}")